#!/bin/sh
workers=$(cat "$JSPIDER_HOME/config/cluster.properties" | sed -nr "s/^cluster.worker([0-9]+).host=([0-9]+.[0-9]+.[0-9]+.[0-9]+)/\2/p")
for worker in $workers
do
{
    workerHome=$(ssh $worker "source /etc/profile; mkdir -p \$JSPIDER_HOME; echo \$JSPIDER_HOME");
    rsync -av $JSPIDER_HOME/* --exclude-from="$JSPIDER_HOME/bin/updateExclude" $worker:$workerHome
}
done